image: gitpod/workspace-full

tasks:
    - name: Install genezio
      before: npm install -g genezio@latest
      command: genezio --version
ports:
    - name: vite-port
      port: 5173
      onOpen: ignore
      visibility: public
    - name: genezio-port
      port: 8083
      onOpen: ignore
      visibility: public

